### ISSUE TITLE
Why dose I(x;y)>=I(E;y) hold in the `Proof of Theorem 1' 

### ISSUE THREAD

**Issue by FlyGreyWolf** [donghao51/SimMMDG#5]
according the data processing inequality, we have:
X->Z->Y,  I(X;Y)<=I(Z;Y)

In the ``proof of theorem 1'' of your paper, 
for x->g(x)->y, 
is this supposed to be  
``I(x;y)<=I(g(x);y)" instead of `` I(x;y)>=I(E;y)'' ?

**Comment by donghao51** [comment]
hello, please check the data processing inequality (https://en.wikipedia.org/wiki/Data_processing_inequality), we have X->Y->Z, I(X;Y)>=I(X;Z)

**Comment by FlyGreyWolf** [comment]
> hello, please check the data processing inequality (https://en.wikipedia.org/wiki/Data_processing_inequality), we have X->Y->Z, I(X;Y)>=I(X;Z)

OK, I got it. Thanks.
