### ISSUE TITLE
About parameters

### ISSUE THREAD

**Issue by lihongzhao99** [donghao51/SimMMDG#7]
Hi, why different parameters for different cross domains?

python train_video_flow_audio_EPIC_SimMMDG.py 
D2 D3 to D1 --trans_hidden_num 1024
D1 D2 to D3 --alpha_trans 1.0

The same for MOOSA
python train_video_flow_audio_EPIC_MOOSA.py
D2 D3 to D1 --mask_ratio 0.7 --entropy_min_weight 0.001
D1 D3 to D2 --mask_ratio 0.7 --entropy_min_weight 0.1
D1 D2 to D3 --mask_ratio 0.3 --entropy_min_weight 0.1

**Comment by donghao51** [comment]
Hi, we find that the default parameters work well in most cases. However, due to huge domain differences, in some cases we finetune the parameters to achieve better results.
